[kijanikiosk]
api ansible_host=44.234.152.165
logs ansible_host=35.86.17.212
payments ansible_host=184.32.32.128

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/terraform-key-new.pem
